[application]
name = "Bashellit"
icon = ["icon.png"]

[web.app]

# HTML title tag content
title = "Bashellit"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

script = []

[bundle]
identifier = "com.bashellit"
publisher = "Cyprien"
icon = ["assets/app-icon.png"]